export interface GalleryImage
{
    src: string
    alt: string
    title: string
}

export const galleryImages: GalleryImage[] = [{ src: "/gallery/pastor-phil-cool-flexin-jesus.jpg", alt: "Pastor Phil Cool Flexin Jesus", title: "Pastor Phil Cool Flexin Jesus" },
{ src: "/gallery/phil-sandra-magic.jpg", alt: "Phil Sandra Magic", title: "Phil Sandra Magic" },
{ src: "/gallery/phil-on-the-mic.png", alt: "Phil On The Mic", title: "Phil On The Mic" },
{ src: "/gallery/white-hat-phil.jpg", alt: "White Hat Phil", title: "White Hat Phil" },
{ src: "/gallery/armed-dangerous-phil.jpg", alt: "Armed Dangerous Phil", title: "Armed Dangerous Phil" },
{ src: "/gallery/set-free-soldiers-bike.jpeg", alt: "Set Free Soldiers Bike", title: "Set Free Soldiers Bike" },
{ src: "/gallery/ryan-ellis-phil.jpeg", alt: "Ryan Ellis Phil", title: "Ryan Ellis Phil" },
{ src: "/gallery/shoe-fits-phil.png", alt: "Shoe Fits Phil", title: "Shoe Fits Phil" },
{ src: "/gallery/sandra-phil-red-tie.png", title: "Sandra with Phil wearing a red tie", alt: "Sandra with Phil wearing a red tie" },
{ src: "/gallery/phil-new-song-church.jpg", alt: "Phil New Song Church", title: "Phil New Song Church" },
{ src: "/gallery/chief-posing-with turtle-and friend.png", title: "Chief posing with Trutle", alt: "Chief posing with Turtle" },
{ src: "/gallery/phil-love-this-guy.JPG", alt: "Phil Love This Guy", title: "Phil - Love This Guy" },
{ src: "/gallery/chill-and-chief-suits.png", alt: "Chill and Chief suits", title: "Chill and Chief suits" },
{ src: "/gallery/phil-anaheim-brewery.png", alt: "Phil at Anaheim Brewery", title: "Phil at Anaheim Brewery" },
{ src: "/gallery/fieldy-phil.jpg", alt: "Fieldy Phil", title: "Fieldy Phil" },
{ src: "/gallery/phil-sandra-wedding.jpg", alt: "Phil Sandra Wedding", title: "Phil Sandra Wedding" },
{src:"/gallery/phil-with-manny.png", alt:"Phil with Manny", title:"Phil with Manny"},
{ src: "/gallery/humbled-chiefism.png", alt: "Chiefism is humbled", title: "Chiefism is humbled" },
{ src: "/gallery/old-school-biker-phil.png", alt: "Old School Biker Phil", title: "Old School Biker Phil" },
{src:"/gallery/jesus-forever-set-free-vest.png", alt:"Jesus Forever Set Free Vest", title:"Jesus Forever Set Free Vest"},
{ src: "/gallery/ufc-fighter-phil.png", alt: "UFC Fighter with Phil", title: "UFC Fighter with Phil" },
{ src: "/gallery/worldshaker-event-phil.png", title: "Worldshaker Society Event", alt: "Worldshaker Society Event" },
{ src: "/gallery/phil-love-this-guy.JPG", alt: "Phil Love This Guy", title: "Phil - Love This Guy" },
{ src: "/gallery/phil-broken-people.png", alt: "Phil broken people", title: "Phil broken people" },
{ src: "/gallery/dying-breed-phil.png", alt: "Dying Breed shirt Phil", title: "Dying Breed shirt Phil" },
{ src: "/gallery/phil-sandra-with-girls.png", alt: "Sandra and Phil with girls", title: "Sandra and Phil with girls" },
{ src: "/gallery/san-diego-set-free.jpg", alt: "San Diego Set Free", title: "San Diego Set Free" },
{ src: "/gallery/crew-at-phils.jpeg", title: "Group biker photo with Phil at his house", alt: "Group biker photo with Phil at his house" }
]
export const galleryImages2: GalleryImage[] = [{ src: "/gallery/chief-in-front-the-palace.jpg", alt: "Chief in front of the palace", title: "Chief in front of the palace" },
{ src: "/gallery/joe-phil-jen-sandra-wedding.jpg", alt: "Joe, Phil, Jen, and Sandra wedding", title: "Joe, Phil, Jen, and Sandra at Joe's wedding" },
{ src: "/gallery/pastor-phil-cool-flexin-jesus.jpg", alt: "Pastor Phil Cool Flexin Jesus", title: "Pastor Phil Cool Flexin Jesus" },
{ src: "/gallery/set-free-biker-ministry-phil.jpeg", alt: "Set Free Biker Ministry Phil", title: "Set Free Biker Ministry Phil" },
{ src: "/gallery/pastor-phil-set-free-anaheim-baptism.jpg", alt: "Pastor Phil Set Free Anaheim Baptism", title: "Pastor Phil Baptism - Anaheim" },
{ src: "/gallery/phil-love-this-guy.JPG", alt: "Phil Love This Guy", title: "Phil - Love This Guy" },
{ src: "/gallery/i-am-redemption.jpg", alt: "I Am Redemption", title: "I Am Redemption" },
{ src: "/gallery/risky-speaking-truth.jpg", alt: "Risky Speaking Truth", title: "Risky Speaking Truth" },
{ src: "/gallery/phil-hugging-black-guy.jpg", alt: "Phil Hugging Black Guy", title: "Phil Hugging Friend" },
{ src: "/gallery/dj-anthony.jpg", alt: "DJ Anthony", title: "DJ Anthony" },
{ src: "/gallery/chill-phil-finger.jpg", alt: "Chill Phil Finger", title: "Chill Phil" },
{ src: "/gallery/anthony-rachel-fun.jpg", alt: "Anthony and Rachel Fun", title: "Anthony and Rachel Fun" },
{ src: "/gallery/phil-sunday-setfree-hat.jpg", alt: "Phil Sunday Set Free Hat", title: "Phil Sunday Set Free Hat" },
{ src: "/gallery/red-chill-handshake.jpg", alt: "Red Chill Handshake", title: "Red Chill Handshake" },
{ src: "/gallery/chief-preaching.jpg", alt: "Chief Preaching", title: "Chief Preaching" },
{ src: "/gallery/chill-phil.jpg", alt: "Chill Phil", title: "Chill Phil" },
{ src: "/gallery/sunday-soberiety-celebration.jpg", alt: "Sunday Soberiety Celebration", title: "Sunday Soberiety Celebration" },
{ src: "/gallery/bible-nerd.jpg", alt: "Bible Nerd", title: "Bible Nerd" },
{ src: "/gallery/happy-phil.jpg", alt: "Happy Phil", title: "Happy Phil" },
{ src: "/gallery/Set-Free-2.jpg", alt: "Set Free Church Crowd", title: "Set Free Church Crowd" },
{ src: "/gallery/BrianAngelaHands.jpg", alt: "Brian and Angela Hands", title: "Brian and Angela Hands" },
{ src: "/gallery/sunday-angela.jpg", alt: "Sunday Angela", title: "Sunday Angela" },
{ src: "/gallery/way-back-when.JPG", alt: "Way Back When", title: "Way Back When" },
{ src: "/gallery/set-free-soldiers-bike.jpeg", alt: "Set Free Soldiers Bike", title: "Set Free Soldiers Bike" },
{ src: "/gallery/phil-sandra-magic.jpg", alt: "Phil Sandra Magic", title: "Phil Sandra Magic" },
{ src: "/gallery/hooligan-phll-preaching.jpg", alt: "Hooligan Phil Preaching", title: "Hooligan Phil Preaching" },
{ src: "/gallery/PastorBrian.jpg", alt: "Pastor Brian", title: "Pastor Brian" },
{ src: "/gallery/PhilSandra.jpg", alt: "Phil Sandra", title: "Phil Sandra" },
{ src: "/gallery/white-hat-phil.jpg", alt: "White Hat Phil", title: "White Hat Phil" },
{ src: "/gallery/solo-setfree-bike.jpg", alt: "Solo Set Free Bike", title: "Solo Set Free Bike" },
{ src: "/gallery/sandra-fieldy-phil.jpg", alt: "Sandra Fieldy Phil", title: "Sandra Fieldy Phil" },
{ src: "/gallery/san-diego-set-free.jpg", alt: "San Diego Set Free", title: "San Diego Set Free" },
{ src: "/gallery/phil-sandra-wedding.jpg", alt: "Phil Sandra Wedding", title: "Phil Sandra Wedding" },
{ src: "/gallery/phil-palace-church.jpg", alt: "Phil Palace Church", title: "Phil Palace Church" },
{ src: "/gallery/phil-new-song-church.jpg", alt: "Phil New Song Church", title: "Phil New Song Church" },
{ src: "/gallery/phil-judo.jpg", alt: "Phil Judo", title: "Phil Judo" },
{ src: "/gallery/phil-house-fullerton-shirt.jpg", alt: "Phil House Fullerton Shirt", title: "Phil House Fullerton Shirt" },
{ src: "/gallery/phil-holding-blocks.jpeg", alt: "Phil Holding Blocks", title: "Phil Holding Blocks" },
{ src: "/gallery/phil-christmas-family.jpg", alt: "Phil Christmas Family", title: "Phil Christmas Family" },
{ src: "/gallery/phil-biker-salvation.jpg", alt: "Phil Biker Salvation", title: "Phil Biker Salvation" },
{ src: "/gallery/jesus-forever-set-free.JPG", alt: "Jesus Forever Set Free", title: "Jesus Forever Set Free" },
{ src: "/gallery/fieldy-phil.jpg", alt: "Fieldy Phil", title: "Fieldy Phil" },
{ src: "/gallery/armed-dangerous-phil.jpg", alt: "Armed Dangerous Phil", title: "Armed Dangerous Phil" },
]